### ISSUE TITLE
Error when installing media-libs/directx-headers

### ISSUE THREAD

**Issue by dstanberry** [Phoenix591/gentoo-overlay#2]
I created /etc/env.d/99wsl-env with LDPATH and LDLIB and ran env-update after.
But I get the following:
```
test/meson.build:5:0: ERROR: C++ shared or static library 'd3d12' not found
```

How did you provide this lib?

**Comment by Phoenix591** [comment]
its part of wslg, what version of windows do you have installed? its in 11
for sure, also possibly 10 21h2

**Comment by dstanberry** [comment]
Is there some other env that needs to be set? I'm on 11 and I have the nvidia drivers for wsl installed, but I've had to manually add setup the env variables so far (like xdg_runtime_dir, pulse, etc.)

After setting LDPATH and running `env-update && source /etc/profile` I get
```
>>> Regenerating /etc/ld.so.cache...
/sbin/ldconfig: /usr/lib/wsl/lib/libcuda.so.1 is not a symbolic link
```

Is this the same for you?

**Comment by dstanberry** [comment]
I got it to work after adding `LIBRARY_PATH` to the file in `/etc/env.d/99wsl-env`.
The ebuild may need to reflect that. FWIW I'm on meson 0.59.1
