### ISSUE TITLE
GOverlay 0.8.1 does not show mangohud overlay on preview window

### ISSUE THREAD

**Issue by zewm** [Phoenix591/gentoo-overlay#3]
The preview window in GOverlay (spinning colored cube) doesn't show the mangohud initial overlay or subsequent modifications to the overlay. Manipulating options and saving still leaves it unshown.

Mangohud overlay is working on glxgears, vkcube and actual games. This is the only "3D" window that it doesn't show up.

I also tried invoking goverlay with mangohud command and ENV variable and it still refuses to show on GOverlay preview window.

When tested on another distribution (Arch), it worked as intended. Both opengl and vulkan USE flags were enabled during compilation.

- KDE Plasma Version: 5.24.5
- KDE Framework: 5.92.0
- QT Version: 5.15.3
- Kernel: 5.15.41-gentoo-dist (64 bit)
- Graphics Platform: X11

- CPU: Intel 10850k
- GPU: Nvidia RTX 3090
- Nvidia Driver: 515.48.07

**Comment by Phoenix591** [comment]
I don't actually use either goverlay or mangohud. It was a sample ebuild I threw in a while ago for someone else. 

I think I may have seen something about one of these two needing a qt5pas patch, but I'm not willing to go into deep troubleshooting on something I don't use

58b1e780eb9340408a2bf72146bc10cb361aafd0 masked for removal
