### ISSUE TITLE
app-emulation/vmware-player depends on a (recently) masked package

### ISSUE THREAD

**Issue by LeXofLeviafan** [Phoenix591/gentoo-overlay#5]
I recently got the following warning when running `emerge`:
```
!!! The following installed packages are masked:
- gnome-base/gconf-3.2.6-r6::gentoo (masked by: package.mask)
/usr/ports/gentoo/profiles/package.mask:
# Matt Turner <mattst88@gentoo.org> (2023-03-04)
# Long deprecated, GNOME 2-era packages.
# Removal on 2023-04-04. Bug #873841
```
After a quick check I found out that the reason I have `gconf` installed is because it's pulled in as dependency by `vmware-player` – both v16 and v17 ebuilds have `gconf` listed in their rdeps.

**Comment by Phoenix591** [comment]
my pc recently died so it'l be a little bit so I can test myself. Mind
seeing if they moved away from it? see if it still works if you emerge -C
it?

**Comment by LeXofLeviafan** [comment]
Well it does _appear_ to work without it… Then again, I've no clue what it was using `gconf` for in the first place :sweat_smile:
