### ISSUE TITLE
Please migrate to Guru

### ISSUE THREAD

**Issue by vitaly-zdanevich** [Phoenix591/gentoo-overlay#8]
Why:

1. Other users will be able to maintain these builds
2. Automatic validations on Guru
3. Guru is official overlay
4. People will review and help

https://github.com/gentoo/guru

**Comment by Phoenix591** [comment]
Honestly, I've seen people put some hot garbage into Guru.

Any packages in particular you'd want to see somewhere more official though? I'm at least somewhat open to proxy maintaining ( and getting into portage itself) some stuff I actually use which is  mostly everything in here.

**Comment by Phoenix591** [comment]
I've put certbot-dns-cloudflare and it's two deps into Guru ( https://github.com/gentoo/guru/commit/6a307885359e65e49ae02c11f11fec5477c4b988 ). Any particular requests for other things? Otherwise I'm going to stick with things I watch super closely, maybe slowly add one or two more things idk.

**Comment by vitaly-zdanevich** [comment]
Thanks!

**Comment by Phoenix591** [comment]
Alrighty, as mentioned earlier I'll put things that I definitely care about and can maintain and feel that others can definitely use into Guru. I'll still keep some things here, but will also maintain the things I leave here.

If anyone later on requests something specific from here to go in there I'll probably do it.
